language: python
python:
 - '2.7'
 - '3.6'
 - '3.7'
 - '3.8'
 - '3.9'
install:
 - pip install flake8 coverage pytest codecov
 - pip install -r requirements.txt
script:
 - flake8
 - coverage run -m pytest
 - codecov
